version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
    - /Users/njayanandana/Documents/Projects/training/ncinga/004-recap/data-dir:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080