apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      volumes:
      - name: mysqlpasswd
        secret:
          secretName: mysecret
      containers:
      - image: busybox
        name: busybox
        command:
        - /bin/sh
        - -c
        - sleep 3600;
        env:
        - name: MYSQL_PASS
          valueFrom:
             secretKeyRef:
               name: mysecret
               key: mysqlpw
        envFrom:
        - secretRef:
             name: mysecret
        volumeMounts:
        - name: mysqlpasswd
          mountPath: /creds/passwd.txt
          subPath: mysqlpw

