apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ncinga
  name: all-access-ns
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-access-cluster
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]