apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      
      containers:
      - image: busybox
        name: busybox
        command:
        - /bin/sh
        - -c
        - sleep 10
        resources: {}
      restartPolicy: OnFailure
status: {}
