apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ghost
  name: ghost
  namespace: ghost
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    readinessProbe:
       httpGet:
        path: /
        port: 80
  - image: ghost
    name: ghost
    ports:
    - containerPort: 2368
    resources:
      requests:
         cpu: 500m
         memory: 200Mi
      limits:
         cpu: 1
         memory: 500Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}


