apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    app: nginx
    company: ncinga
  name: default
  namespace: ncinga
spec:
  containers:
  - image: nginx:alpine
    name: nginx-container
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 100Mi  
  dnsPolicy: ClusterFirst
  restartPolicy: Never
