apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
     kubernetes.io/change-cause: "Updated CPU to 120"
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 120m
status: {}
